### PR TITLE
Fix error with updating info on me/update page

### PR DESCRIPTION
**Pull request by sukhada**
Fix for this issue: https://github.com/350org/action-tools/issues/358

### CODE REVIEW

**Review by JamieDraper — APPROVED** [review]
Looks good, nice job!

**Comment by cjmabry** [comment]
@sukhada ++ good work, would this be something Tryn could QA? If so, could you add some QA notes?

**Comment by sukhada** [comment]
@cjmabry yes, but I think we probably want to get it out soonish? I believe @rachelhbd has already QA'ed!

**Comment by rachelhbd** [comment]
Thanks folks! yes ++ @sukhada I've taken a look and  since it's a bugfix we can go straight to production

**Comment by cjmabry** [comment]
Copy that sounds good!

**Pull request merged**
